### ISSUE TITLE
Coordination

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vector-tile#1]
The goal of this library is to start sharing core code for working with Mapbox Vector Tiles (https://github.com/mapbox/vector-tile-spec/) across key C++ codebases implementing the specification. The focus will be on Mapbox maintained code, but this library should be easily pluggable anywhere.

This ticket stands to track broadly:
- the upstream needs for this library
- the downstream consumers this library is targeting.
#### Upstream
- Will definitely depend on protozero 1.x
  - Team to coordinate with: @joto 
- Will likely depend on `mapbox::variant`
  - Team to coordinate with: @artemp
- Will likely depend on a first 1.x release of https://github.com/mapbox/geometry.hpp
  - Team to coordinate with: @artemp @jfirebaugh 
#### Downstream
- **tippecanoe**: 
  - Relevant files:
    - https://github.com/mapbox/tippecanoe/blob/master/mvt.hh
    - https://github.com/mapbox/tippecanoe/blob/master/mvt.cc
  - Team to coordinate with: @ericfischer
- **OSRM** (https://github.com/Project-OSRM/osrm-backend)
  - Relevant files:
    - https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/vector_tile.hpp
    - https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/plugins/tile.cpp
  - Team to coordinate with: @lbud @danpat
- **Mapbox GL**:  
  - Relevant files:
    - https://github.com/mapbox/mapbox-gl-native/blob/master/src/mbgl/tile/vector_tile.hpp
  - Team to coordinate with: @kkaefer
- **mapnik-vector-tile** (https://github.com/mapbox/mapnik-vector-tile)
  - Relevant files:
    - https://github.com/mapbox/mapnik-vector-tile/blob/master/src/vector_tile_config.hpp
  - Team to coordinate with: @mapsam @jakepruitt @flippmoke

**Comment by flippmoke** [comment]
We will need to move clipper to a header only repository as well more then likely

**Comment by kkaefer** [comment]
Why clipper?

**Comment by flippmoke** [comment]
If the goal is to make vector-tile its own standalone library, clipping is going to be a very important part of the process. So much so that we will need to modify the existing clipper library to be header only. This will also be a big win because we can then use the clipper with geometry.hpp in other locations.

**Comment by joto** [comment]
We should probably differentiate here between the code that is concerned with the details of the vector tile format itself and the code that decides which data to put into which vector tile. Clipping is something not everybody might need (or need to do it in a different way that what a library provides).

I envision the vector tile library more as a low level helper library translating from concepts such as *layers* and *features* to the varints and delta encodings of the underlying protocol buffer format. Ideally in a way that's as much as possible indifferent to geometry formats used etc. Anything more than that could be in an extra library or in optional parts of the library.

**Comment by kkaefer** [comment]
I agree with @joto that this library should just be concerned with the storage format, and possibly doing some light validation, but nothing beyond that. This is also how the JS library works.

**Comment by springmeyer** [comment]
👍  also agree that this effort should focus on the storage format first, and dodge the complexity of clipping and other things like polygon cleaning. While those are critical, let's focus on the potential code sharing before those are needed.

**Comment by springmeyer** [comment]
Back here to close recap where we are:

> We will need to move clipper to a header only repository as well more then likely

Done, and @flippmoke masterfully re-wrote it at the same time: https://github.com/mapbox/wagyu

> We should probably differentiate here between the code that is concerned with the details of the vector tile format itself and the code that decides which data to put into which vector tile.

We've done this. The vtile specific code now lives in the minimalistic [vtzero library](https://github.com/mapbox/vtzero). That means that this repo now will be the higher level API on top of `vtzero` - that development we'll track at https://github.com/mapbox/vector-tile/issues/23
