### ISSUE TITLE
More unit tests of decoder

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vector-tile#12]
Currently the decoder is only being tested against one sample tile (https://github.com/mapbox/vector-tile/blob/743776310f871cea0be9a050fe78afc68d81b1e6/test/unit/vector_tile.test.cpp#L55-L81). Next we need to build out the tests to ensure the decoder is working against all valid and invalid tiles from  https://github.com/mapbox/mvt-fixtures

**Comment by mapsam** [comment]
Hey @springmeyer - starting to take a look at adding more unit tests so I can also get a sense of how to improve the docs at `mapbox/mvt-fixtures`. Here's a working example of asserting that vector tiles throws on a tile without a version field:

```cpp
TEST_CASE( "Invalid tile failures" ) {
    SECTION( "Tile has no layer" ) {
        try {
            std::string buffer = open_tile("test/mvt-fixtures/fixtures/invalid/Layer-version-none.mvt");
            mapbox::vector_tile::buffer tile(buffer);
            const auto layer_names = tile.layerNames();
            auto layer_ptr = tile.getLayer("layer_name");
            REQUIRE(false);
        } catch (std::runtime_error& e) {
            std::string err_message(e.what());
            REQUIRE( err_message == "missing required field: version " );
        }
    }

    SECTION("more invalid fixtures") { ... }
}
```

What do you think?

**Comment by springmeyer** [comment]
Closing, this level of testing will be handled when we add tests to vtzero: https://github.com/mapbox/vtzero/issues/2
