### ISSUE TITLE
Future development

### ISSUE THREAD

**Issue by springmeyer** [mapbox/vector-tile#23]
Development on this library is currently paused.

This is because the efforts of @mapbox/core-tech are going towards building out https://github.com/mapbox/vtzero: a more minimalistic, flexible, and efficient implementation (compared to the current API here in master).

The next steps are to work on https://github.com/mapbox/vtzero/milestone/1. Once that is done, we will recommence development on this library by rebranching from `hpp-skel`.

 The goals of the future design will be to add high level APIs on top of `vtzero` that deal with:

phase 1:

 - Decoding geometries into geometry.hpp (https://github.com/mapbox/geometry.hpp)
 - Decoding properties into variant.hpp (https://github.com/mapbox/variant)

phase 2:

(via spatial-algorithms)

 - Handling projection and other coordinate transformations into tile coords
 - Clipping and simplification (https://github.com/mapbox/wagyu)
 - Compression (https://github.com/mapbox/gzip-hpp)

/cc @mapbox/core-tech @mapbox/gl-core @mapbox/directions @kkaefer @jfirebaugh @anandthakker @ericfischer

**Comment by springmeyer** [comment]
Update: vtzero is v1.x is nearing completion by @joto. The work that remains in vtzero is mainly tests and docs (https://github.com/mapbox/vtzero/milestone/1). Therefore it is time to start working on re-building this library as a higher level impl on top of vtzero. @flippmoke is leading this effort. @flippmoke can you map out the steps you are seeing to get this done below?

/cc @artemp

**Comment by springmeyer** [comment]
Status update:
 - https://github.com/mapbox/vtzero is stabilizing and ready to use. The HEAD version is now working well in https://github.com/mapbox/mvt-cruncher and https://github.com/mapbox/vtquery (and other internal projects at Mapbox). We are looking for more feedback however before releasing the first version, since changing things after release is harder than changing things now.
 - vtzero still only has one dependency: protozero. And therefore it is very low level and integration should enable the highest performance possible for downstream users.
 - @flippmoke has been prototyping a future, higher level API on top of vtzero that depends on an experimental version of geometry.hpp (https://github.com/mapbox/geometry.hpp/tree/algorithms), variant, and vtzero/protozero: https://github.com/mapbox/vector-tile/tree/2.x

The assumption is that some consumers will use the vtzero APIs directly, while others will use the mapbox/vector-tile 2.x APIs more and more as they develop.

**Comment by flippmoke** [comment]
Closing this ticket, now tracking via the milestone. Individual tasks have been issued out as much as possible. https://github.com/mapbox/vector-tile/milestone/2
