### ISSUE TITLE
publish to mason

### ISSUE THREAD

**Issue by mapsam** [mapbox/vector-tile#6]
Let's get vector-tile published to mason so we can include it in other projects (instead of copy-pasting). 

https://github.com/mapbox/hpp-skel#deploy-to-mason-packing

cc @springmeyer

**Comment by springmeyer** [comment]
👍  per https://github.com/mapbox/vector-tile/pull/4#issuecomment-238960512 lets do a v1.0.0-rc1 first (fully packaged). Then if that looks good, we can issue an official v1.0.0.

**Comment by mapsam** [comment]
`1.0.0-rc1` has been published to mason! Working on `1.0.0-rc2` after some tests over here #8

**Comment by springmeyer** [comment]
This is in place thanks to @mapsam. Now working on publishing the upcoming rc4 at https://github.com/mapbox/mason/pull/233.
